- name: Install mongodb-org
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: Download and extract the src from git 
  ansible.builtin.unarchive:
    src: https://raw.githubusercontent.com/stans-robot-project/mongodb/main/mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo
    remote_src: yes

- name: Start service mongod
  ansible.builtin.service:
    name: mongod
    state: start
    enabled: yes

- name: clean-up the  directory
  ansible.builtin.shell:
    cmd:

- name: Start service Nginx
  ansible.builtin.service:
    name: mongod
    state: restarted
    enabled: yes



