- name: Copy a conf file 
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb-org
  ansible.builtin.package:
    name: mongodb-org
    state: installed

- name: Replace old hostname with new hostname (requires Ansible >= 2.4)
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start service mongod
  ansible.builtin.service:
    name: mongod
    state: restarted
    
- name: Download and extract the src from git 
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Run tasks/other.yaml instead of 'main'
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Load Catalogue Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop: 
    - catalogue 
    - users


# - name: Run a js file containing MongoDB commands with pseudo-idempotency
#   community.mongodb.mongodb_shell:
#     file: "/tmp/mongodb-main/catalogue.js"
#     idempotent: yes

# - name: Run a js file containing MongoDB commands with pseudo-idempotency
#   community.mongodb.mongodb_shell:
#     file: "/tmp/mongodb-main/users.js"
#     idempotent: yes

# - name: clean-up the  directory
#   ansible.builtin.shell:
#     cmd:

# - name: Start service Nginx
#   ansible.builtin.service:
#     name: mongod
#     state: restarted
#     enabled: yes



