- name: Demo on privilege escalation
  hosts: all 
  # become: yes
  become: yes 
  tasks: 
    - name: Running a shell commands 
      ansible.builtin.shell: id
      register: OUT

    - name: Printing the out variable 
      ansible.builtin.debug: 
        msg: "{{OUT.stdout}}" 


    - name: Running a shell commands 
      ansible.builtin.shell: id
      become_user: centos
      register: OUT

    - name: Printing the out variable 
      ansible.builtin.debug: 
        msg: "{{OUT.stdout}}" 
