- name: Play1 
  hosts: all 
  tasks:
      - name: Print Hello from task1 of play1 
        ansible.builtin.debug:
              msg: Hai from task1 of play1 
      - name: Print Hello from task1 of play2 
        ansible.builtin.debug:
              msg: Hai from task2 of play2 


- name: Afsarplaybook
  hosts: dev
  tasks:
     - name: "Afsar task1 in Afsarplaybook"
       ansible.builtin.debug:
            msg: "Hi, this is afsarplaybook for test"
